<a href="https://colab.research.google.com/github/Cooljoe67/ML_DSAI/blob/main/UML_Day_2_Warmup__K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# ID of the Google Sheet for student food preferences
sheet_id = "1L7obsP1jXD3hfU7Tf01iEgmJemfh45TT"

# Title of the Google Sheet
sheet_name = "1410882745"

# URL to download the Google Sheet as a CSV
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={sheet_name}"

# Create a Pandas DataFrame from the CSV data
foods_df = pd.read_csv(url, index_col="student")

# Drop age - we only care about food here (we'll use age when we learn to scale data)
# Drop favorite_color - why can't we use a color to calculate distances
to_drop = ['age', 'favorite_color']
foods_df = foods_df.drop(columns=to_drop)
foods_df

,broccoli,brussels_sprouts,steak,pumpkin_pie,pizza,seafood,olives,pesto_pasta,curry
student,,,,,,,,,
Aysenur,5,6,10,7,8,10,10,8,7
Bengü,6,10,10,1,9,9,10,5,9
Elcin,9,9,10,3,10,10,10,10,10
Linh,6,3,9,4,6,8,3,5,4
Lisa,9,8,2,4,10,1,2,5,9
Marcus,6,7,9,3,9,8,8,7,6
Mariia T,9,7,0,10,6,7,7,6,8
Marvin,8,5,10,1,9,8,1,8,10
Niels,7,8,9,3,9,3,5,8,10
Sonja,8,5,10,5,9,7,10,9,9
Stefano,8,0,5,5,10,0,0,10,8
Tatiana,7,9,10,1,7,10,10,8,10
Sama/Marlo,8,5,10,9,9,9,7,10,5

#### Exercise 1: Import the K-Means model and initialize it with a random state and number of clusters

In [6]:
from sklearn.cluster import KMeans

r_seed = 123

my_KMeans_model = KMeans(n_clusters=3, random_state=r_seed,verbose=1)

##### Hint:

Take a look at the documentation [here](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html)<br>
At the very top it says `class sklearn.cluster.KMeans(`... This is kind of like a file path telling us where to find the model in the library. So to import it we run `from sklearn.cluster import KMeans`.<br><br>
To initialize the model we call it like a function with parameters and assign the result to a variable: `model = KMeans(param = _____, param = _____)` You can look at the documentation to find what the names are for the parameters that we have to use to initialize it with a random state and number of clusters.

In [9]:
my_KMeans_model.__dict__

{'n_clusters': 3,
 'init': 'k-means++',
 'max_iter': 300,
 'tol': 0.0001,
 'n_init': 'auto',
 'verbose': 1,
 'random_state': 123,
 'copy_x': True,
 'algorithm': 'lloyd',
 'feature_names_in_': array(['broccoli', 'brussels_sprouts', 'steak', 'pumpkin_pie', 'pizza',
        'seafood', 'olives', 'pesto_pasta', 'curry'], dtype=object),
 'n_features_in_': 9,
 '_tol': np.float64(0.0006648257725180802),
 '_n_init': 1,
 '_algorithm': 'lloyd',
 '_n_threads': 8,
 'cluster_centers_': array([[ 7. ,  6.7,  9.7,  3.7,  8.5,  8.2,  7.4,  7.8,  8. ],
        [ 8.5,  4. ,  3.5,  4.5, 10. ,  0.5,  1. ,  7.5,  8.5],
        [ 9. ,  7. ,  0. , 10. ,  6. ,  7. ,  7. ,  6. ,  8. ]]),
 '_n_features_out': 3,
 'labels_': array([0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0], dtype=int32),
 'inertia_': 407.3999999999999,
 'n_iter_': 2}

#### Exercise 2: Fit the model to the food data imported above

In [17]:
my_KMeans_model.fit(foods_df)

Initialization complete
Iteration 0, inertia 626.0.
Iteration 1, inertia 407.3999999999999.
Converged at iteration 1: strict convergence.

c:\Users\Marcus\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=3, random_state=123, verbose=1)

##### Hint:

Fit the model to the data using the `.fit()` method

#### Exercise 3: Extract the cluster assignments from the model and add them as a new column to `foods_df`

In [18]:
foods_df["cluster"] = my_KMeans_model.labels_
foods_df

,broccoli,brussels_sprouts,steak,pumpkin_pie,pizza,seafood,olives,pesto_pasta,curry,cluster
student,,,,,,,,,,
Aysenur,5,6,10,7,8,10,10,8,7,0
Bengü,6,10,10,1,9,9,10,5,9,0
Elcin,9,9,10,3,10,10,10,10,10,0
Linh,6,3,9,4,6,8,3,5,4,0
Lisa,9,8,2,4,10,1,2,5,9,1
Marcus,6,7,9,3,9,8,8,7,6,0
Mariia T,9,7,0,10,6,7,7,6,8,2
Marvin,8,5,10,1,9,8,1,8,10,0
Niels,7,8,9,3,9,3,5,8,10,0
Sonja,8,5,10,5,9,7,10,9,9,0
Stefano,8,0,5,5,10,0,0,10,8,1
Tatiana,7,9,10,1,7,10,10,8,10,0
Sama/Marlo,8,5,10,9,9,9,7,10,5,0

##### Hint:

Extract a list of cluster assignments from the model using `model.labels_`

#### Exercise 4: Sort the data frame by the cluster assignments to more easily see the groupings

In [20]:
foods_df.sort_values(by="cluster")

,broccoli,brussels_sprouts,steak,pumpkin_pie,pizza,seafood,olives,pesto_pasta,curry,cluster
student,,,,,,,,,,
Aysenur,5,6,10,7,8,10,10,8,7,0
Bengü,6,10,10,1,9,9,10,5,9,0
Elcin,9,9,10,3,10,10,10,10,10,0
Linh,6,3,9,4,6,8,3,5,4,0
Marcus,6,7,9,3,9,8,8,7,6,0
Marvin,8,5,10,1,9,8,1,8,10,0
Niels,7,8,9,3,9,3,5,8,10,0
Sonja,8,5,10,5,9,7,10,9,9,0
Tatiana,7,9,10,1,7,10,10,8,10,0
Sama/Marlo,8,5,10,9,9,9,7,10,5,0
Lisa,9,8,2,4,10,1,2,5,9,1
Stefano,8,0,5,5,10,0,0,10,8,1
Mariia T,9,7,0,10,6,7,7,6,8,2

##### Hint:

`df.sort_values()`

#### BONUS: Try it again with a different number of clusters

In [21]:
my_KMeans_model2 = KMeans(n_clusters=6, random_state=r_seed)
my_KMeans_model2.fit(foods_df)
foods_df["cluster2"] = my_KMeans_model2.labels_
foods_df.sort_values(by="cluster2")

c:\Users\Marcus\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

,broccoli,brussels_sprouts,steak,pumpkin_pie,pizza,seafood,olives,pesto_pasta,curry,cluster,cluster2
student,,,,,,,,,,,
Aysenur,5,6,10,7,8,10,10,8,7,0,0
Elcin,9,9,10,3,10,10,10,10,10,0,0
Sonja,8,5,10,5,9,7,10,9,9,0,0
Sama/Marlo,8,5,10,9,9,9,7,10,5,0,0
Lisa,9,8,2,4,10,1,2,5,9,1,1
Mariia T,9,7,0,10,6,7,7,6,8,2,2
Bengü,6,10,10,1,9,9,10,5,9,0,3
Linh,6,3,9,4,6,8,3,5,4,0,3
Marcus,6,7,9,3,9,8,8,7,6,0,3
Tatiana,7,9,10,1,7,10,10,8,10,0,3
Stefano,8,0,5,5,10,0,0,10,8,1,4
Marvin,8,5,10,1,9,8,1,8,10,0,5
Niels,7,8,9,3,9,3,5,8,10,0,5

##### Hint:

Simply adjust the `n_clusters` parameter when initializing and rerun the code you wrote before